insert into songs (Title, Artist, Genre) values ('Pop Power', 'Kara Walker', 'rock');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'David Hockney', 'blues');
insert into songs (Title, Artist, Genre) values ('Infinite Grooves', 'Yoko Ono', 'jazz');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Cindy Sherman', 'electronic');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Barbara Kruger', 'rap');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Damien Hirst', 'jazz');
insert into songs (Title, Artist, Genre) values ('Midnight Memories', 'David Hockney', 'punk');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Andy Warhol', 'electronic');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'Jeff Koons', 'indie');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Jean-Michel Basquiat', 'country');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Roy Lichtenstein', 'jazz');
insert into songs (Title, Artist, Genre) values ('Heartbeat Highway', 'Keith Haring', 'electronic');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Kara Walker', 'electronic');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Yayoi Kusama', 'rock');
insert into songs (Title, Artist, Genre) values ('Heartbeat Highway', 'Cindy Sherman', 'rock');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Keith Haring', 'jazz');
insert into songs (Title, Artist, Genre) values ('Dreamland', 'Keith Haring', 'rock');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'David Hockney', 'country');
insert into songs (Title, Artist, Genre) values ('Starstruck', 'Roy Lichtenstein', 'indie');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Jean-Michel Basquiat', 'folk');
insert into songs (Title, Artist, Genre) values ('Radiant Rhythms', 'Yayoi Kusama', 'soul');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Yoko Ono', 'indie');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Jeff Koons', 'rock');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Jean-Michel Basquiat', 'indie');
insert into songs (Title, Artist, Genre) values ('Heavenly Beats', 'Roy Lichtenstein', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Banksy', 'rock');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Roy Lichtenstein', 'country');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Yayoi Kusama', 'blues');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Keith Haring', 'electronic');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Barbara Kruger', 'jazz');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Barbara Kruger', 'jazz');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Yoko Ono', 'country');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Andy Warhol', 'country');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Kaws', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Damien Hirst', 'metal');
insert into songs (Title, Artist, Genre) values ('Heartbeat Highway', 'Barbara Kruger', 'blues');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Andy Warhol', 'reggae');
insert into songs (Title, Artist, Genre) values ('Lost in the Music', 'Damien Hirst', 'indie');
insert into songs (Title, Artist, Genre) values ('Midnight Memories', 'Damien Hirst', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Jean-Michel Basquiat', 'classical');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Takashi Murakami', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Damien Hirst', 'rap');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Banksy', 'classical');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Damien Hirst', 'punk');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Keith Haring', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Barbara Kruger', 'jazz');
insert into songs (Title, Artist, Genre) values ('Heartbeat Highway', 'Keith Haring', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Sunshine and Rainbows', 'Kaws', 'indie');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Cindy Sherman', 'metal');
insert into songs (Title, Artist, Genre) values ('Midnight Memories', 'Kaws', 'country');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Damien Hirst', 'classical');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Kara Walker', 'metal');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Andy Warhol', 'indie');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Roy Lichtenstein', 'indie');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Damien Hirst', 'punk');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Yayoi Kusama', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Banksy', 'country');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Andy Warhol', 'folk');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Yayoi Kusama', 'rap');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Cindy Sherman', 'rap');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Yayoi Kusama', 'rock');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Damien Hirst', 'rap');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'David Hockney', 'rap');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Damien Hirst', 'pop');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Jean-Michel Basquiat', 'folk');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Damien Hirst', 'rap');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'David Hockney', 'pop');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Yoko Ono', 'indie');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Jeff Koons', 'jazz');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'David Hockney', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Cindy Sherman', 'country');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Banksy', 'country');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Roy Lichtenstein', 'rock');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Andy Warhol', 'jazz');
insert into songs (Title, Artist, Genre) values ('Party All Night', 'David Hockney', 'jazz');
insert into songs (Title, Artist, Genre) values ('Dreamland', 'Roy Lichtenstein', 'soul');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Andy Warhol', 'indie');
insert into songs (Title, Artist, Genre) values ('Magic Melodies', 'Cindy Sherman', 'jazz');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'Jean-Michel Basquiat', 'folk');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Jeff Koons', 'reggae');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Takashi Murakami', 'rap');
insert into songs (Title, Artist, Genre) values ('Summer Love', 'Takashi Murakami', 'rap');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Barbara Kruger', 'reggae');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Barbara Kruger', 'metal');
insert into songs (Title, Artist, Genre) values ('Funky Town', 'Takashi Murakami', 'jazz');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Kara Walker', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Takashi Murakami', 'blues');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Roy Lichtenstein', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Andy Warhol', 'rock');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Kara Walker', 'soul');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Takashi Murakami', 'pop');
insert into songs (Title, Artist, Genre) values ('Groove Machine', 'Roy Lichtenstein', 'metal');
insert into songs (Title, Artist, Genre) values ('Summer Love', 'Jeff Koons', 'electronic');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Kaws', 'country');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Banksy', 'folk');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Andy Warhol', 'rap');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Takashi Murakami', 'soul');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'Jean-Michel Basquiat', 'reggae');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Kaws', 'indie');
insert into songs (Title, Artist, Genre) values ('Wild and Free', 'Yoko Ono', 'reggae');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Damien Hirst', 'punk');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Jean-Michel Basquiat', 'metal');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Kaws', 'indie');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Yoko Ono', 'soul');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'David Hockney', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Yoko Ono', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Jean-Michel Basquiat', 'pop');
insert into songs (Title, Artist, Genre) values ('Magic Melodies', 'Yoko Ono', 'country');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Jeff Koons', 'electronic');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Cindy Sherman', 'electronic');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Yayoi Kusama', 'rock');
insert into songs (Title, Artist, Genre) values ('Sunshine and Rainbows', 'Kaws', 'indie');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Jeff Koons', 'classical');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Damien Hirst', 'country');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Takashi Murakami', 'metal');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Yayoi Kusama', 'reggae');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Andy Warhol', 'classical');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Jean-Michel Basquiat', 'country');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Keith Haring', 'soul');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Kara Walker', 'indie');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Kara Walker', 'blues');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Barbara Kruger', 'pop');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Barbara Kruger', 'soul');
insert into songs (Title, Artist, Genre) values ('Party All Night', 'Kara Walker', 'punk');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Cindy Sherman', 'indie');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Keith Haring', 'soul');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Yoko Ono', 'metal');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Barbara Kruger', 'jazz');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Jeff Koons', 'electronic');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Barbara Kruger', 'electronic');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Cindy Sherman', 'classical');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Barbara Kruger', 'metal');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'David Hockney', 'punk');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Banksy', 'pop');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'David Hockney', 'country');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Kara Walker', 'blues');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Roy Lichtenstein', 'punk');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Keith Haring', 'metal');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Banksy', 'rock');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Takashi Murakami', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Kaws', 'country');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Banksy', 'soul');
insert into songs (Title, Artist, Genre) values ('Wild and Free', 'Jean-Michel Basquiat', 'classical');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Yoko Ono', 'punk');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Keith Haring', 'rap');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Jeff Koons', 'electronic');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Keith Haring', 'reggae');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Kara Walker', 'country');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Kara Walker', 'jazz');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Jeff Koons', 'jazz');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Jeff Koons', 'classical');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'David Hockney', 'jazz');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'David Hockney', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Andy Warhol', 'country');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Jean-Michel Basquiat', 'country');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Cindy Sherman', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Takashi Murakami', 'classical');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Yayoi Kusama', 'soul');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Jean-Michel Basquiat', 'reggae');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Yayoi Kusama', 'metal');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Keith Haring', 'indie');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Keith Haring', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Yoko Ono', 'jazz');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'David Hockney', 'classical');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Yoko Ono', 'metal');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Yoko Ono', 'electronic');
insert into songs (Title, Artist, Genre) values ('Midnight Memories', 'Roy Lichtenstein', 'electronic');
insert into songs (Title, Artist, Genre) values ('Heartbeat Highway', 'Jeff Koons', 'classical');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Jean-Michel Basquiat', 'punk');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'David Hockney', 'pop');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Jean-Michel Basquiat', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Andy Warhol', 'soul');
insert into songs (Title, Artist, Genre) values ('Groove Machine', 'Roy Lichtenstein', 'rock');
insert into songs (Title, Artist, Genre) values ('Moonlit Madness', 'Barbara Kruger', 'pop');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Roy Lichtenstein', 'rap');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Damien Hirst', 'country');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Roy Lichtenstein', 'jazz');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Damien Hirst', 'classical');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Yoko Ono', 'indie');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Damien Hirst', 'jazz');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Banksy', 'soul');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'David Hockney', 'electronic');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Roy Lichtenstein', 'soul');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Andy Warhol', 'punk');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Banksy', 'electronic');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'Roy Lichtenstein', 'country');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Keith Haring', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Kaws', 'country');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'David Hockney', 'blues');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Damien Hirst', 'electronic');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Andy Warhol', 'reggae');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'David Hockney', 'reggae');
insert into songs (Title, Artist, Genre) values ('Summer Love', 'Yoko Ono', 'jazz');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Andy Warhol', 'jazz');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Yoko Ono', 'blues');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Jean-Michel Basquiat', 'jazz');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Barbara Kruger', 'country');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Yayoi Kusama', 'soul');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Kara Walker', 'punk');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Jeff Koons', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Kara Walker', 'pop');
insert into songs (Title, Artist, Genre) values ('Groove Machine', 'Cindy Sherman', 'rock');
insert into songs (Title, Artist, Genre) values ('Infinite Grooves', 'Keith Haring', 'pop');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Cindy Sherman', 'metal');
insert into songs (Title, Artist, Genre) values ('Funky Town', 'Jeff Koons', 'rock');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Damien Hirst', 'classical');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Kaws', 'electronic');
insert into songs (Title, Artist, Genre) values ('Heavenly Beats', 'David Hockney', 'soul');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Yayoi Kusama', 'reggae');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Kara Walker', 'electronic');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Cindy Sherman', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Cindy Sherman', 'country');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Kaws', 'pop');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Kara Walker', 'soul');
insert into songs (Title, Artist, Genre) values ('Midnight Memories', 'Kaws', 'metal');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Kaws', 'country');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'David Hockney', 'pop');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'David Hockney', 'soul');
insert into songs (Title, Artist, Genre) values ('Heavenly Beats', 'Jeff Koons', 'metal');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Jeff Koons', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Barbara Kruger', 'punk');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Roy Lichtenstein', 'classical');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Yayoi Kusama', 'country');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Damien Hirst', 'jazz');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Kara Walker', 'folk');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Yayoi Kusama', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Kara Walker', 'rock');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Barbara Kruger', 'country');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Kaws', 'blues');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Barbara Kruger', 'blues');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Jeff Koons', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Roy Lichtenstein', 'rap');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Yoko Ono', 'soul');
insert into songs (Title, Artist, Genre) values ('Heartbreak Hotel', 'Damien Hirst', 'jazz');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'Kara Walker', 'pop');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Keith Haring', 'metal');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Cindy Sherman', 'blues');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Jean-Michel Basquiat', 'folk');
insert into songs (Title, Artist, Genre) values ('Moonlit Madness', 'Jean-Michel Basquiat', 'metal');
insert into songs (Title, Artist, Genre) values ('Dreamy Disco', 'Yayoi Kusama', 'classical');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Cindy Sherman', 'blues');
insert into songs (Title, Artist, Genre) values ('Summer Love', 'Kara Walker', 'blues');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Barbara Kruger', 'rock');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Kara Walker', 'punk');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Cindy Sherman', 'pop');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Keith Haring', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Keith Haring', 'jazz');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Barbara Kruger', 'indie');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Cindy Sherman', 'rock');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Roy Lichtenstein', 'metal');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Jean-Michel Basquiat', 'classical');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'Takashi Murakami', 'indie');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Cindy Sherman', 'country');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Barbara Kruger', 'country');
insert into songs (Title, Artist, Genre) values ('Party All Night', 'Kara Walker', 'pop');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Damien Hirst', 'indie');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Roy Lichtenstein', 'metal');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'Jeff Koons', 'folk');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Yoko Ono', 'jazz');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Jean-Michel Basquiat', 'folk');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Barbara Kruger', 'folk');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Cindy Sherman', 'country');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Keith Haring', 'classical');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Jean-Michel Basquiat', 'indie');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Keith Haring', 'metal');
insert into songs (Title, Artist, Genre) values ('Heartbeat Highway', 'Yoko Ono', 'folk');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Banksy', 'electronic');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Keith Haring', 'folk');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Keith Haring', 'metal');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Yayoi Kusama', 'rock');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Damien Hirst', 'indie');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Banksy', 'pop');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Takashi Murakami', 'electronic');
insert into songs (Title, Artist, Genre) values ('Starstruck', 'Jean-Michel Basquiat', 'electronic');
insert into songs (Title, Artist, Genre) values ('Party All Night', 'Jean-Michel Basquiat', 'blues');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Takashi Murakami', 'soul');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Barbara Kruger', 'reggae');
insert into songs (Title, Artist, Genre) values ('Moonlit Madness', 'Barbara Kruger', 'blues');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Kara Walker', 'soul');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'David Hockney', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Takashi Murakami', 'classical');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Barbara Kruger', 'electronic');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Andy Warhol', 'punk');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Damien Hirst', 'reggae');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Jean-Michel Basquiat', 'punk');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Jeff Koons', 'classical');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Kara Walker', 'classical');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Yayoi Kusama', 'punk');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Cindy Sherman', 'rap');
insert into songs (Title, Artist, Genre) values ('Sunshine and Rainbows', 'Yoko Ono', 'rap');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'David Hockney', 'pop');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Keith Haring', 'indie');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Barbara Kruger', 'metal');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Keith Haring', 'blues');
insert into songs (Title, Artist, Genre) values ('Heavenly Beats', 'David Hockney', 'rock');
insert into songs (Title, Artist, Genre) values ('Radiant Rhythms', 'Yayoi Kusama', 'pop');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'David Hockney', 'reggae');
insert into songs (Title, Artist, Genre) values ('Funky Town', 'Kaws', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'David Hockney', 'jazz');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Kara Walker', 'rap');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Roy Lichtenstein', 'metal');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Cindy Sherman', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Heartbreak Hotel', 'Yayoi Kusama', 'punk');
insert into songs (Title, Artist, Genre) values ('Moonlit Madness', 'Roy Lichtenstein', 'rap');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Jean-Michel Basquiat', 'pop');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Barbara Kruger', 'soul');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Keith Haring', 'rock');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Yayoi Kusama', 'jazz');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Andy Warhol', 'blues');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'Yayoi Kusama', 'punk');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Cindy Sherman', 'soul');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Kaws', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Andy Warhol', 'electronic');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Yoko Ono', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Yoko Ono', 'country');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Barbara Kruger', 'metal');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Takashi Murakami', 'electronic');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Yayoi Kusama', 'classical');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'David Hockney', 'soul');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Andy Warhol', 'blues');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Andy Warhol', 'classical');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Yoko Ono', 'punk');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Banksy', 'soul');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Kara Walker', 'pop');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Jeff Koons', 'country');
insert into songs (Title, Artist, Genre) values ('Moonlit Madness', 'Banksy', 'country');
insert into songs (Title, Artist, Genre) values ('Heavenly Beats', 'Banksy', 'punk');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Kara Walker', 'country');
insert into songs (Title, Artist, Genre) values ('Dreamy Disco', 'Keith Haring', 'rock');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Yayoi Kusama', 'classical');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Andy Warhol', 'soul');
insert into songs (Title, Artist, Genre) values ('Love on the Dancefloor', 'Roy Lichtenstein', 'classical');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Yoko Ono', 'blues');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Andy Warhol', 'blues');
insert into songs (Title, Artist, Genre) values ('Moonlit Madness', 'Jeff Koons', 'country');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Keith Haring', 'rock');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Cindy Sherman', 'indie');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'Jeff Koons', 'soul');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Cindy Sherman', 'metal');
insert into songs (Title, Artist, Genre) values ('Party All Night', 'Keith Haring', 'rock');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Keith Haring', 'folk');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Jean-Michel Basquiat', 'metal');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Yayoi Kusama', 'reggae');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Damien Hirst', 'folk');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'David Hockney', 'country');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Kara Walker', 'pop');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Damien Hirst', 'rock');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Jean-Michel Basquiat', 'soul');
insert into songs (Title, Artist, Genre) values ('Heavenly Beats', 'Takashi Murakami', 'punk');
insert into songs (Title, Artist, Genre) values ('Moonlit Madness', 'Keith Haring', 'folk');
insert into songs (Title, Artist, Genre) values ('Heartbreak Hotel', 'Roy Lichtenstein', 'classical');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Roy Lichtenstein', 'rap');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Keith Haring', 'jazz');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Barbara Kruger', 'soul');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Kara Walker', 'punk');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Barbara Kruger', 'pop');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Kara Walker', 'pop');
insert into songs (Title, Artist, Genre) values ('Starstruck', 'Yayoi Kusama', 'blues');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Roy Lichtenstein', 'folk');
insert into songs (Title, Artist, Genre) values ('Dreamy Disco', 'Jean-Michel Basquiat', 'reggae');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Yoko Ono', 'jazz');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Jean-Michel Basquiat', 'metal');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Roy Lichtenstein', 'folk');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Banksy', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Jeff Koons', 'soul');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Takashi Murakami', 'electronic');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Keith Haring', 'punk');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Takashi Murakami', 'country');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Kaws', 'rap');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Kaws', 'punk');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Yoko Ono', 'reggae');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Cindy Sherman', 'classical');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Kara Walker', 'punk');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Barbara Kruger', 'country');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Yoko Ono', 'blues');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Keith Haring', 'indie');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Kara Walker', 'jazz');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Kara Walker', 'indie');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Kara Walker', 'rock');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Jeff Koons', 'rock');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'Keith Haring', 'punk');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Barbara Kruger', 'rock');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Barbara Kruger', 'rock');
insert into songs (Title, Artist, Genre) values ('Infinite Grooves', 'Barbara Kruger', 'blues');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Jeff Koons', 'folk');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Andy Warhol', 'country');
insert into songs (Title, Artist, Genre) values ('Dreamy Disco', 'Yayoi Kusama', 'rap');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Takashi Murakami', 'classical');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Takashi Murakami', 'blues');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Jean-Michel Basquiat', 'country');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Jeff Koons', 'country');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Damien Hirst', 'reggae');
insert into songs (Title, Artist, Genre) values ('Starstruck', 'Takashi Murakami', 'soul');
insert into songs (Title, Artist, Genre) values ('Sunshine and Rainbows', 'Kara Walker', 'rap');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Keith Haring', 'reggae');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Jean-Michel Basquiat', 'jazz');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'Keith Haring', 'jazz');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Banksy', 'folk');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Jean-Michel Basquiat', 'electronic');
insert into songs (Title, Artist, Genre) values ('Summer Love', 'Andy Warhol', 'reggae');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Jean-Michel Basquiat', 'punk');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Andy Warhol', 'pop');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Kara Walker', 'blues');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Barbara Kruger', 'indie');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Andy Warhol', 'punk');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'David Hockney', 'indie');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Kara Walker', 'metal');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Jeff Koons', 'soul');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Cindy Sherman', 'metal');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Barbara Kruger', 'jazz');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Takashi Murakami', 'rap');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Kaws', 'blues');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Yoko Ono', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Takashi Murakami', 'electronic');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Keith Haring', 'punk');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Takashi Murakami', 'jazz');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Takashi Murakami', 'metal');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Andy Warhol', 'rap');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Cindy Sherman', 'rock');
insert into songs (Title, Artist, Genre) values ('Heartbreak Hotel', 'Cindy Sherman', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Jeff Koons', 'soul');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Roy Lichtenstein', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Jean-Michel Basquiat', 'reggae');
insert into songs (Title, Artist, Genre) values ('Infinite Grooves', 'Keith Haring', 'pop');
insert into songs (Title, Artist, Genre) values ('Infinite Grooves', 'Roy Lichtenstein', 'metal');
insert into songs (Title, Artist, Genre) values ('Love on the Dancefloor', 'Jeff Koons', 'jazz');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Yoko Ono', 'rap');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Takashi Murakami', 'jazz');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'David Hockney', 'pop');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Andy Warhol', 'soul');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Barbara Kruger', 'classical');
insert into songs (Title, Artist, Genre) values ('Heartbreak Hotel', 'Barbara Kruger', 'rap');
insert into songs (Title, Artist, Genre) values ('Starstruck', 'Yoko Ono', 'metal');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Barbara Kruger', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Damien Hirst', 'rock');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Damien Hirst', 'classical');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Cindy Sherman', 'reggae');
insert into songs (Title, Artist, Genre) values ('Radiant Rhythms', 'Roy Lichtenstein', 'punk');
insert into songs (Title, Artist, Genre) values ('Radiant Rhythms', 'Barbara Kruger', 'electronic');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Barbara Kruger', 'punk');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Banksy', 'country');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Yayoi Kusama', 'pop');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Barbara Kruger', 'indie');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Barbara Kruger', 'soul');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Cindy Sherman', 'jazz');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Damien Hirst', 'soul');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Jeff Koons', 'soul');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'David Hockney', 'metal');
insert into songs (Title, Artist, Genre) values ('Dreamland', 'Takashi Murakami', 'folk');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Banksy', 'classical');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Takashi Murakami', 'rap');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Cindy Sherman', 'rap');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Takashi Murakami', 'rock');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Kara Walker', 'indie');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'Barbara Kruger', 'country');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Banksy', 'soul');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Cindy Sherman', 'electronic');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Banksy', 'electronic');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Keith Haring', 'indie');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Kaws', 'blues');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Banksy', 'folk');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Keith Haring', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'Roy Lichtenstein', 'rap');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Takashi Murakami', 'pop');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Andy Warhol', 'soul');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Yayoi Kusama', 'jazz');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Banksy', 'jazz');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Yoko Ono', 'folk');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Barbara Kruger', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Kaws', 'classical');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Yayoi Kusama', 'blues');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Jean-Michel Basquiat', 'country');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Kaws', 'pop');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Keith Haring', 'indie');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Jean-Michel Basquiat', 'punk');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Kara Walker', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Yoko Ono', 'punk');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Yayoi Kusama', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dreamland', 'Barbara Kruger', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Cindy Sherman', 'soul');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Kaws', 'folk');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Yoko Ono', 'folk');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Damien Hirst', 'punk');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Damien Hirst', 'reggae');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Kaws', 'rock');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Yoko Ono', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dreamland', 'Andy Warhol', 'rap');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Cindy Sherman', 'punk');
insert into songs (Title, Artist, Genre) values ('Sunshine and Rainbows', 'Yoko Ono', 'blues');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Jeff Koons', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Barbara Kruger', 'indie');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'David Hockney', 'rap');
insert into songs (Title, Artist, Genre) values ('Magic Melodies', 'Barbara Kruger', 'jazz');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Keith Haring', 'reggae');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Yoko Ono', 'punk');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'David Hockney', 'jazz');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Jeff Koons', 'rock');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Jeff Koons', 'folk');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Yoko Ono', 'soul');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Damien Hirst', 'classical');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Kaws', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Damien Hirst', 'soul');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Kara Walker', 'punk');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Roy Lichtenstein', 'reggae');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Damien Hirst', 'reggae');
insert into songs (Title, Artist, Genre) values ('Moonlit Madness', 'Banksy', 'rap');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Jeff Koons', 'indie');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Damien Hirst', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Kara Walker', 'blues');
insert into songs (Title, Artist, Genre) values ('Magic Melodies', 'Keith Haring', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Cindy Sherman', 'rap');
insert into songs (Title, Artist, Genre) values ('Radiant Rhythms', 'Jean-Michel Basquiat', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Banksy', 'reggae');
insert into songs (Title, Artist, Genre) values ('Infinite Grooves', 'Yoko Ono', 'punk');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Andy Warhol', 'metal');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Yayoi Kusama', 'pop');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Roy Lichtenstein', 'jazz');
insert into songs (Title, Artist, Genre) values ('Party All Night', 'Takashi Murakami', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Kaws', 'rock');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Jeff Koons', 'jazz');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Andy Warhol', 'classical');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Cindy Sherman', 'electronic');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Andy Warhol', 'punk');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Jean-Michel Basquiat', 'pop');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Andy Warhol', 'electronic');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Jeff Koons', 'jazz');
insert into songs (Title, Artist, Genre) values ('Magic Melodies', 'Yoko Ono', 'soul');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Jean-Michel Basquiat', 'rap');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Yayoi Kusama', 'country');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Keith Haring', 'punk');
insert into songs (Title, Artist, Genre) values ('Sunshine and Rainbows', 'Takashi Murakami', 'blues');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Takashi Murakami', 'folk');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Yayoi Kusama', 'blues');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'David Hockney', 'metal');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Jean-Michel Basquiat', 'electronic');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Damien Hirst', 'jazz');
insert into songs (Title, Artist, Genre) values ('Summer Love', 'Keith Haring', 'soul');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Andy Warhol', 'country');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Jean-Michel Basquiat', 'metal');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Keith Haring', 'reggae');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Kaws', 'folk');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Jeff Koons', 'indie');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Kara Walker', 'electronic');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Andy Warhol', 'folk');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Jeff Koons', 'country');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Yayoi Kusama', 'country');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Barbara Kruger', 'metal');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'David Hockney', 'rock');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Andy Warhol', 'pop');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Keith Haring', 'metal');
insert into songs (Title, Artist, Genre) values ('Moonlit Madness', 'Jean-Michel Basquiat', 'soul');
insert into songs (Title, Artist, Genre) values ('Magic Melodies', 'Barbara Kruger', 'blues');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Damien Hirst', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Radiant Rhythms', 'Barbara Kruger', 'electronic');
insert into songs (Title, Artist, Genre) values ('Starstruck', 'Roy Lichtenstein', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Barbara Kruger', 'classical');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Barbara Kruger', 'indie');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Takashi Murakami', 'rock');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'Cindy Sherman', 'electronic');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Jeff Koons', 'metal');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'David Hockney', 'pop');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Kara Walker', 'metal');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Keith Haring', 'jazz');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Jeff Koons', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Cindy Sherman', 'punk');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Barbara Kruger', 'soul');
insert into songs (Title, Artist, Genre) values ('Summer Love', 'Yoko Ono', 'blues');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Cindy Sherman', 'country');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'David Hockney', 'jazz');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Takashi Murakami', 'pop');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Kaws', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Jeff Koons', 'country');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Jean-Michel Basquiat', 'metal');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Jean-Michel Basquiat', 'rap');
insert into songs (Title, Artist, Genre) values ('Heavenly Beats', 'Barbara Kruger', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Takashi Murakami', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Cindy Sherman', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Yayoi Kusama', 'indie');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Andy Warhol', 'reggae');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Andy Warhol', 'reggae');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Kaws', 'country');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Jeff Koons', 'metal');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Banksy', 'jazz');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Kara Walker', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'David Hockney', 'pop');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Kaws', 'electronic');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Kaws', 'classical');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Barbara Kruger', 'indie');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Roy Lichtenstein', 'indie');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Jeff Koons', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Kara Walker', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Takashi Murakami', 'indie');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Jean-Michel Basquiat', 'indie');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Kara Walker', 'jazz');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Kaws', 'jazz');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Kaws', 'electronic');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Keith Haring', 'classical');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Keith Haring', 'jazz');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Banksy', 'rap');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Kaws', 'blues');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Yayoi Kusama', 'reggae');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Cindy Sherman', 'rock');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Barbara Kruger', 'electronic');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Damien Hirst', 'electronic');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Banksy', 'metal');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Jeff Koons', 'indie');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Andy Warhol', 'folk');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Roy Lichtenstein', 'reggae');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Yayoi Kusama', 'reggae');
insert into songs (Title, Artist, Genre) values ('Groove Machine', 'Banksy', 'soul');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Yoko Ono', 'country');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Jeff Koons', 'folk');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Keith Haring', 'folk');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Jeff Koons', 'blues');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'Roy Lichtenstein', 'jazz');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Roy Lichtenstein', 'electronic');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Yoko Ono', 'pop');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Jeff Koons', 'electronic');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Keith Haring', 'punk');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Roy Lichtenstein', 'country');
insert into songs (Title, Artist, Genre) values ('Party All Night', 'Takashi Murakami', 'rock');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Jeff Koons', 'country');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'David Hockney', 'reggae');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Yoko Ono', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Damien Hirst', 'folk');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Keith Haring', 'reggae');
insert into songs (Title, Artist, Genre) values ('Infinite Grooves', 'Keith Haring', 'electronic');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Jeff Koons', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Kara Walker', 'reggae');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Barbara Kruger', 'rock');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Damien Hirst', 'soul');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Kaws', 'folk');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Jeff Koons', 'rap');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Jean-Michel Basquiat', 'rock');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'Jean-Michel Basquiat', 'country');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Roy Lichtenstein', 'classical');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Kara Walker', 'metal');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Jeff Koons', 'reggae');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Barbara Kruger', 'soul');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Keith Haring', 'country');
insert into songs (Title, Artist, Genre) values ('Radiant Rhythms', 'Keith Haring', 'classical');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Yoko Ono', 'reggae');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Damien Hirst', 'jazz');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'David Hockney', 'pop');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Kara Walker', 'folk');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Damien Hirst', 'folk');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Kaws', 'pop');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Damien Hirst', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Cindy Sherman', 'folk');
insert into songs (Title, Artist, Genre) values ('Sunshine and Rainbows', 'Kaws', 'rock');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Jeff Koons', 'classical');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Roy Lichtenstein', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Damien Hirst', 'indie');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'Banksy', 'rap');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Roy Lichtenstein', 'metal');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Jeff Koons', 'indie');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Yoko Ono', 'indie');
insert into songs (Title, Artist, Genre) values ('Heavenly Beats', 'Jean-Michel Basquiat', 'jazz');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Jean-Michel Basquiat', 'country');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Jeff Koons', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'Cindy Sherman', 'electronic');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'David Hockney', 'jazz');
insert into songs (Title, Artist, Genre) values ('Groove Machine', 'Takashi Murakami', 'indie');
insert into songs (Title, Artist, Genre) values ('Radiant Rhythms', 'Keith Haring', 'classical');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Andy Warhol', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Yayoi Kusama', 'electronic');
insert into songs (Title, Artist, Genre) values ('Party All Night', 'Jeff Koons', 'metal');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'David Hockney', 'metal');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Jean-Michel Basquiat', 'electronic');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Damien Hirst', 'metal');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Andy Warhol', 'country');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Banksy', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Roy Lichtenstein', 'indie');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Kara Walker', 'punk');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Yoko Ono', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Jean-Michel Basquiat', 'rock');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Yayoi Kusama', 'folk');
insert into songs (Title, Artist, Genre) values ('Dreamland', 'Yayoi Kusama', 'electronic');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Andy Warhol', 'reggae');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Yoko Ono', 'pop');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Yayoi Kusama', 'reggae');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Roy Lichtenstein', 'electronic');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Takashi Murakami', 'reggae');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Takashi Murakami', 'soul');
insert into songs (Title, Artist, Genre) values ('Starstruck', 'Yoko Ono', 'punk');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Takashi Murakami', 'indie');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Barbara Kruger', 'jazz');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Andy Warhol', 'indie');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Barbara Kruger', 'blues');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Banksy', 'reggae');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Barbara Kruger', 'jazz');
insert into songs (Title, Artist, Genre) values ('Dreamland', 'Takashi Murakami', 'electronic');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Cindy Sherman', 'metal');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Cindy Sherman', 'jazz');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Andy Warhol', 'rap');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Barbara Kruger', 'country');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Banksy', 'blues');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Yayoi Kusama', 'indie');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Jeff Koons', 'electronic');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Cindy Sherman', 'reggae');
insert into songs (Title, Artist, Genre) values ('Love on the Dancefloor', 'Keith Haring', 'metal');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Cindy Sherman', 'pop');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Cindy Sherman', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Roy Lichtenstein', 'blues');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Barbara Kruger', 'rap');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Cindy Sherman', 'jazz');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Barbara Kruger', 'jazz');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Jean-Michel Basquiat', 'punk');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Yayoi Kusama', 'electronic');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'David Hockney', 'rock');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Keith Haring', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Kara Walker', 'punk');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Kara Walker', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Jean-Michel Basquiat', 'folk');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Kaws', 'classical');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Damien Hirst', 'soul');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Damien Hirst', 'jazz');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Takashi Murakami', 'country');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Barbara Kruger', 'rock');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Barbara Kruger', 'classical');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Takashi Murakami', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Roy Lichtenstein', 'indie');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Roy Lichtenstein', 'classical');
insert into songs (Title, Artist, Genre) values ('Radiant Rhythms', 'Kaws', 'indie');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Kara Walker', 'soul');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Kara Walker', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Wild and Free', 'Jeff Koons', 'metal');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'Andy Warhol', 'folk');
insert into songs (Title, Artist, Genre) values ('Groove Machine', 'Banksy', 'metal');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Yayoi Kusama', 'rap');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Keith Haring', 'electronic');
insert into songs (Title, Artist, Genre) values ('Summer Love', 'Keith Haring', 'pop');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'David Hockney', 'soul');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Yoko Ono', 'electronic');
insert into songs (Title, Artist, Genre) values ('Heartbreak Hotel', 'Kaws', 'rap');
insert into songs (Title, Artist, Genre) values ('Groove Machine', 'Banksy', 'punk');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Kaws', 'rap');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'David Hockney', 'electronic');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Jean-Michel Basquiat', 'electronic');
insert into songs (Title, Artist, Genre) values ('Magic Melodies', 'Cindy Sherman', 'metal');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Banksy', 'indie');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Andy Warhol', 'country');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Yoko Ono', 'rock');
insert into songs (Title, Artist, Genre) values ('Heartbeat Highway', 'Takashi Murakami', 'jazz');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Kaws', 'soul');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Jeff Koons', 'rock');
insert into songs (Title, Artist, Genre) values ('City Lights', 'Yoko Ono', 'classical');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Kaws', 'blues');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Keith Haring', 'metal');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Roy Lichtenstein', 'rap');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Roy Lichtenstein', 'country');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'David Hockney', 'country');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Jean-Michel Basquiat', 'classical');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Cindy Sherman', 'electronic');
insert into songs (Title, Artist, Genre) values ('Dreamy Disco', 'Cindy Sherman', 'blues');
insert into songs (Title, Artist, Genre) values ('Magic Melodies', 'Takashi Murakami', 'soul');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Keith Haring', 'blues');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Andy Warhol', 'indie');
insert into songs (Title, Artist, Genre) values ('Sunshine and Rainbows', 'Barbara Kruger', 'soul');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Yoko Ono', 'jazz');
insert into songs (Title, Artist, Genre) values ('Sunshine and Rainbows', 'Kara Walker', 'folk');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'David Hockney', 'classical');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Yoko Ono', 'soul');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Roy Lichtenstein', 'pop');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Banksy', 'folk');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Kaws', 'blues');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Yoko Ono', 'country');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Yayoi Kusama', 'blues');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Jean-Michel Basquiat', 'electronic');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'Kara Walker', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Cindy Sherman', 'rap');
insert into songs (Title, Artist, Genre) values ('Moonlit Madness', 'Jean-Michel Basquiat', 'punk');
insert into songs (Title, Artist, Genre) values ('Infinite Grooves', 'Cindy Sherman', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'David Hockney', 'indie');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Jeff Koons', 'classical');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Andy Warhol', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Damien Hirst', 'country');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Kaws', 'pop');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Kara Walker', 'indie');
insert into songs (Title, Artist, Genre) values ('Party All Night', 'Kaws', 'rap');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Roy Lichtenstein', 'rap');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Andy Warhol', 'electronic');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Roy Lichtenstein', 'electronic');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Kara Walker', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'David Hockney', 'classical');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Kara Walker', 'folk');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Kara Walker', 'country');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Yayoi Kusama', 'punk');
insert into songs (Title, Artist, Genre) values ('Heartbeat Highway', 'Roy Lichtenstein', 'metal');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Roy Lichtenstein', 'rap');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Cindy Sherman', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Cindy Sherman', 'classical');
insert into songs (Title, Artist, Genre) values ('Dreamland', 'Jean-Michel Basquiat', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Heartbreak Hotel', 'Takashi Murakami', 'blues');
insert into songs (Title, Artist, Genre) values ('Groove Machine', 'Keith Haring', 'electronic');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Banksy', 'indie');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Damien Hirst', 'rock');
insert into songs (Title, Artist, Genre) values ('Heartbeat Highway', 'Yoko Ono', 'blues');
insert into songs (Title, Artist, Genre) values ('Dreamy Disco', 'Kaws', 'jazz');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Roy Lichtenstein', 'soul');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Andy Warhol', 'country');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Takashi Murakami', 'soul');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Damien Hirst', 'jazz');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Yoko Ono', 'rap');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Roy Lichtenstein', 'indie');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Damien Hirst', 'blues');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Jeff Koons', 'electronic');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'David Hockney', 'folk');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Keith Haring', 'folk');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Keith Haring', 'punk');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Yoko Ono', 'jazz');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Roy Lichtenstein', 'electronic');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Jeff Koons', 'jazz');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Roy Lichtenstein', 'pop');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'David Hockney', 'electronic');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Jean-Michel Basquiat', 'punk');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Jeff Koons', 'rock');
insert into songs (Title, Artist, Genre) values ('Summer Love', 'Roy Lichtenstein', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Roy Lichtenstein', 'rock');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Jeff Koons', 'country');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Kara Walker', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Jeff Koons', 'rap');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Takashi Murakami', 'rap');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Andy Warhol', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Andy Warhol', 'rock');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Yoko Ono', 'rap');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Andy Warhol', 'metal');
insert into songs (Title, Artist, Genre) values ('Heartbreak Hotel', 'Cindy Sherman', 'rock');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Jeff Koons', 'rock');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Kara Walker', 'jazz');
insert into songs (Title, Artist, Genre) values ('Radiant Rhythms', 'Cindy Sherman', 'jazz');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Banksy', 'pop');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Roy Lichtenstein', 'country');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'Barbara Kruger', 'soul');
insert into songs (Title, Artist, Genre) values ('Lost in the Music', 'Cindy Sherman', 'metal');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Keith Haring', 'indie');
insert into songs (Title, Artist, Genre) values ('Sonic Symphony', 'Roy Lichtenstein', 'country');
insert into songs (Title, Artist, Genre) values ('Love on the Dancefloor', 'Barbara Kruger', 'electronic');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Keith Haring', 'blues');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Jeff Koons', 'soul');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Damien Hirst', 'rap');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Andy Warhol', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Love on the Dancefloor', 'Yayoi Kusama', 'classical');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Cindy Sherman', 'indie');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Kara Walker', 'rap');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'David Hockney', 'country');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Andy Warhol', 'pop');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Damien Hirst', 'classical');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Keith Haring', 'blues');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'David Hockney', 'reggae');
insert into songs (Title, Artist, Genre) values ('Wild and Free', 'Andy Warhol', 'folk');
insert into songs (Title, Artist, Genre) values ('Summer Love', 'Yayoi Kusama', 'pop');
insert into songs (Title, Artist, Genre) values ('Summer Love', 'Takashi Murakami', 'metal');
insert into songs (Title, Artist, Genre) values ('Midnight Memories', 'Yoko Ono', 'electronic');
insert into songs (Title, Artist, Genre) values ('Party All Night', 'Jeff Koons', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Keith Haring', 'classical');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Damien Hirst', 'folk');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Cindy Sherman', 'classical');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Yayoi Kusama', 'punk');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Andy Warhol', 'electronic');
insert into songs (Title, Artist, Genre) values ('Heartbreak Hotel', 'Yayoi Kusama', 'rock');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Barbara Kruger', 'rap');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Jean-Michel Basquiat', 'country');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Roy Lichtenstein', 'pop');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Yoko Ono', 'electronic');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Banksy', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Wild and Free', 'Barbara Kruger', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Damien Hirst', 'rock');
insert into songs (Title, Artist, Genre) values ('Dreamy Disco', 'Keith Haring', 'indie');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Cindy Sherman', 'metal');
insert into songs (Title, Artist, Genre) values ('Dreamy Disco', 'Takashi Murakami', 'classical');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Keith Haring', 'folk');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Kaws', 'metal');
insert into songs (Title, Artist, Genre) values ('Dancehall Dreams', 'Yoko Ono', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Damien Hirst', 'metal');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Andy Warhol', 'punk');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Yayoi Kusama', 'classical');
insert into songs (Title, Artist, Genre) values ('Dreamy Disco', 'Kara Walker', 'classical');
insert into songs (Title, Artist, Genre) values ('Melody Magic', 'Takashi Murakami', 'jazz');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Takashi Murakami', 'blues');
insert into songs (Title, Artist, Genre) values ('Funky Town', 'Jeff Koons', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Yoko Ono', 'rap');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Yoko Ono', 'jazz');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Takashi Murakami', 'folk');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Damien Hirst', 'metal');
insert into songs (Title, Artist, Genre) values ('Sunset Serenade', 'Damien Hirst', 'rock');
insert into songs (Title, Artist, Genre) values ('Heartbeat Highway', 'Cindy Sherman', 'classical');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'Barbara Kruger', 'pop');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Yoko Ono', 'rock');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Yoko Ono', 'reggae');
insert into songs (Title, Artist, Genre) values ('Heartbreak Hotel', 'Yoko Ono', 'electronic');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Andy Warhol', 'pop');
insert into songs (Title, Artist, Genre) values ('Moonlit Madness', 'Barbara Kruger', 'country');
insert into songs (Title, Artist, Genre) values ('Heartbreak Hotel', 'Andy Warhol', 'electronic');
insert into songs (Title, Artist, Genre) values ('Groove Machine', 'Kara Walker', 'punk');
insert into songs (Title, Artist, Genre) values ('Rhythmic Romance', 'Jean-Michel Basquiat', 'rock');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Yoko Ono', 'country');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Yayoi Kusama', 'pop');
insert into songs (Title, Artist, Genre) values ('Party All Night', 'Jeff Koons', 'soul');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Yayoi Kusama', 'blues');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Banksy', 'rock');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Jeff Koons', 'soul');
insert into songs (Title, Artist, Genre) values ('Moonlit Madness', 'Cindy Sherman', 'country');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Yayoi Kusama', 'pop');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Barbara Kruger', 'blues');
insert into songs (Title, Artist, Genre) values ('Heartbeat Highway', 'Yoko Ono', 'electronic');
insert into songs (Title, Artist, Genre) values ('Groove Machine', 'Keith Haring', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Golden Days', 'David Hockney', 'rock');
insert into songs (Title, Artist, Genre) values ('Starstruck', 'Barbara Kruger', 'classical');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Andy Warhol', 'electronic');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Takashi Murakami', 'country');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Yoko Ono', 'country');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Roy Lichtenstein', 'blues');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Roy Lichtenstein', 'rock');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Roy Lichtenstein', 'electronic');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Kara Walker', 'country');
insert into songs (Title, Artist, Genre) values ('Dreamy Disco', 'Yayoi Kusama', 'pop');
insert into songs (Title, Artist, Genre) values ('Dancefloor Diva', 'Jean-Michel Basquiat', 'punk');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Keith Haring', 'rock');
insert into songs (Title, Artist, Genre) values ('Sunshine and Rainbows', 'David Hockney', 'pop');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Jean-Michel Basquiat', 'electronic');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Jean-Michel Basquiat', 'metal');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Cindy Sherman', 'jazz');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Jeff Koons', 'country');
insert into songs (Title, Artist, Genre) values ('Rockstar Romance', 'Cindy Sherman', 'electronic');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Kaws', 'country');
insert into songs (Title, Artist, Genre) values ('Summer Love', 'Cindy Sherman', 'blues');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Barbara Kruger', 'country');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Kara Walker', 'country');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Damien Hirst', 'blues');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Keith Haring', 'folk');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Jean-Michel Basquiat', 'folk');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Takashi Murakami', 'soul');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Kara Walker', 'folk');
insert into songs (Title, Artist, Genre) values ('Midnight Memories', 'Banksy', 'soul');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Yoko Ono', 'classical');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Andy Warhol', 'punk');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Kaws', 'blues');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Jean-Michel Basquiat', 'jazz');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'Keith Haring', 'pop');
insert into songs (Title, Artist, Genre) values ('Starstruck', 'Takashi Murakami', 'pop');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'David Hockney', 'rock');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Roy Lichtenstein', 'jazz');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Keith Haring', 'rap');
insert into songs (Title, Artist, Genre) values ('Starlight Serenade', 'Yayoi Kusama', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Heart', 'Barbara Kruger', 'classical');
insert into songs (Title, Artist, Genre) values ('Infinite Grooves', 'Yayoi Kusama', 'punk');
insert into songs (Title, Artist, Genre) values ('Lyrical Love', 'Barbara Kruger', 'classical');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Jeff Koons', 'pop');
insert into songs (Title, Artist, Genre) values ('Dancehall Delight', 'Yayoi Kusama', 'indie');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Jeff Koons', 'electronic');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Damien Hirst', 'blues');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'David Hockney', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Dreamy Disco', 'Yayoi Kusama', 'country');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Andy Warhol', 'pop');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Jeff Koons', 'pop');
insert into songs (Title, Artist, Genre) values ('Summer Vibes', 'Cindy Sherman', 'rock');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Roy Lichtenstein', 'pop');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Roy Lichtenstein', 'country');
insert into songs (Title, Artist, Genre) values ('Dreamy Duet', 'Roy Lichtenstein', 'classical');
insert into songs (Title, Artist, Genre) values ('Neon Nights', 'Damien Hirst', 'jazz');
insert into songs (Title, Artist, Genre) values ('Midnight Memories', 'Banksy', 'indie');
insert into songs (Title, Artist, Genre) values ('Dancefloor Delight', 'Kara Walker', 'indie');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Roy Lichtenstein', 'folk');
insert into songs (Title, Artist, Genre) values ('Melodic Madness', 'Jean-Michel Basquiat', 'reggae');
insert into songs (Title, Artist, Genre) values ('Starry Nights', 'Yayoi Kusama', 'jazz');
insert into songs (Title, Artist, Genre) values ('Magic Melodies', 'Andy Warhol', 'classical');
insert into songs (Title, Artist, Genre) values ('Festival Fever', 'Kara Walker', 'pop');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Keith Haring', 'rock');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Banksy', 'indie');
insert into songs (Title, Artist, Genre) values ('Pop Princess', 'David Hockney', 'jazz');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Jean-Michel Basquiat', 'reggae');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Keith Haring', 'classical');
insert into songs (Title, Artist, Genre) values ('Retro Revival', 'Jean-Michel Basquiat', 'classical');
insert into songs (Title, Artist, Genre) values ('Pop Perfection', 'Jean-Michel Basquiat', 'reggae');
insert into songs (Title, Artist, Genre) values ('Heartbeat Highway', 'Kaws', 'metal');
insert into songs (Title, Artist, Genre) values ('Dreamy Disco', 'Kaws', 'rock');
insert into songs (Title, Artist, Genre) values ('Lost in the Music', 'Kaws', 'punk');
insert into songs (Title, Artist, Genre) values ('Pop Paradise', 'Takashi Murakami', 'blues');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Jean-Michel Basquiat', 'punk');
insert into songs (Title, Artist, Genre) values ('Heavenly Beats', 'Yayoi Kusama', 'soul');
insert into songs (Title, Artist, Genre) values ('Sunshine and Rainbows', 'Jeff Koons', 'rock');
insert into songs (Title, Artist, Genre) values ('Dance Anthem', 'Kara Walker', 'punk');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Banksy', 'rock');
insert into songs (Title, Artist, Genre) values ('Electric Euphoria', 'Jeff Koons', 'rock');
insert into songs (Title, Artist, Genre) values ('Disco Dreamland', 'Barbara Kruger', 'pop');
insert into songs (Title, Artist, Genre) values ('Electric Ecstasy', 'Kaws', 'reggae');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Jean-Michel Basquiat', 'rap');
insert into songs (Title, Artist, Genre) values ('Sonic Bliss', 'Cindy Sherman', 'rap');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Kaws', 'rap');
insert into songs (Title, Artist, Genre) values ('Wild and Free', 'Banksy', 'rock');
insert into songs (Title, Artist, Genre) values ('Luminous Love', 'Jeff Koons', 'folk');
insert into songs (Title, Artist, Genre) values ('Heartbreak Hotel', 'Jean-Michel Basquiat', 'electronic');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Yoko Ono', 'rock');
insert into songs (Title, Artist, Genre) values ('Soulful Sounds', 'Cindy Sherman', 'jazz');
insert into songs (Title, Artist, Genre) values ('Retro Rhythms', 'Jean-Michel Basquiat', 'jazz');
insert into songs (Title, Artist, Genre) values ('Heartfelt Harmony', 'Barbara Kruger', 'soul');
insert into songs (Title, Artist, Genre) values ('Heartbeat Harmony', 'Yoko Ono', 'country');
insert into songs (Title, Artist, Genre) values ('Pop Power', 'Jeff Koons', 'pop');
insert into songs (Title, Artist, Genre) values ('Funky Fresh', 'Jeff Koons', 'punk');
